import { Club } from "../club.model";

export const BARCA: Club = {
  id: "club_barca",
  name: "FC Barcelona",
  nickname: "Blaugrana",
  city: "Barcelona",
  country: "Spain",
  foundedYear: 1899,
  colors: {
    primary: "#A50044",
    secondary: "#004D98",
  },
  logoUrl:
    "https://upload.wikimedia.org/wikipedia/en/thumb/4/47/FC_Barcelona_%28crest%29.svg/1200px-FC_Barcelona_%28crest%29.svg.png",
  stadium: {
    name: "Estadi Olímpic Lluís Companys",
    capacity: 55000,
    averageAttendance: 50000,
    pitchQuality: 92,
  },
  identity: {
    reputation: 97,
    youthRating: 90,
    financialPower: 85,
    infrastructureLevel: 90,
    clubCulture: ["Play Tiki-Taka", "Develop Youth Players"],
    rivalries: ["club_real_madrid", "club_espanyol"],
  },
  squad: [
    "player_ter_stegen",
    "player_inaki_pena",
    "player_kounde",
    "player_araujo",
    "player_cristensen",
    "player_martinez",
    "player_balde",
    "player_cancelo",
    "player_de_jong",
    "player_gundogan",
    "player_pedri",
    "player_gavi",
    "player_romeu",
    "player_fermin_lopez",
    "player_raphinha",
    "player_felix",
    "player_lewandowski",
    "player_yamal",
  ],
  coachId: "coach_xavi",
  assistantCoachId: "coach_assistant_barca",
  staff: {
    medicalTeam: 93,
    scoutingNetwork: 90,
    fitnessStaff: 91,
    moraleStaff: 89,
  },
  competition: {
    league: "Elite 1",
    division: 1,
    currentPosition: 2,
    points: 84,
    goalsFor: 79,
    goalsAgainst: 29,
    recentForm: ["W", "W", "L", "W", "D"],
    isInEuropeanCompetition: true,
  },
  finances: {
    balance: 100_000_000,
    weeklyWageBudget: 4_500_000,
    weeklyWageUsed: 4_300_000,
    incomePerWeek: 6_500_000,
    sponsors: [
      { name: "Spotify", amount: 70_000_000 },
      { name: "Nike", amount: 55_000_000 },
    ],
    ticketPrice: 75,
    merchandising: 40_000_000,
  },
  popularity: {
    fanBaseSize: 16000000,
    fanLoyalty: 78,
    boardExpectations: "Win League and Reach UCL Semi-Final",
    boardTrust: 82,
    mediaReputation: 94,
  },
  storyFlags: {
    takeoverRumor: false,
    fanProtest: false,
    historicWin: false,
  },
};
