import { Club } from "../club.model";

export const PSG: Club = {
  id: "club_psg",
  name: "Paris Saint-Germain",
  nickname: "Les Parisiens",
  city: "Paris",
  country: "France",
  foundedYear: 1970,
  colors: {
    primary: "#004170",
    secondary: "#DA291C",
  },
  logoUrl:
    "https://upload.wikimedia.org/wikipedia/fr/thumb/a/a7/Paris_Saint-Germain_Logo.svg/1200px-Paris_Saint-Germain_Logo.svg.png",
  stadium: {
    name: "Parc des Princes",
    capacity: 47929,
    averageAttendance: 47200,
    pitchQuality: 95,
  },
  identity: {
    reputation: 98,
    youthRating: 80,
    financialPower: 99,
    infrastructureLevel: 95,
    clubCulture: ["Play Attacking Football", "Sign World-Class Players"],
    rivalries: ["club_om"],
  },
  squad: [
    "player_donnarumma",
    "player_navas",
    "player_marquinhos",
    "player_skriniar",
    "player_hernandez",
    "player_hakimi",
    "player_nuno_mendes",
    "player_ugarte",
    "player_vitinha",
    "player_zaïre_emery",
    "player_fabian_ruiz",
    "player_kang_in_lee",
    "player_dembele",
    "player_barcola",
    "player_kolo_muani",
    "player_goncalo_ramos",
    "player_mbappe",
    "player_asensio",
  ],
  coachId: "coach_luis_enrique",
  assistantCoachId: "coach_assistant_psg",
  staff: {
    medicalTeam: 95,
    scoutingNetwork: 88,
    fitnessStaff: 92,
    moraleStaff: 85,
  },
  competition: {
    league: "Ligue 1",
    division: 1,
    currentPosition: 1,
    points: 86,
    goalsFor: 91,
    goalsAgainst: 25,
    recentForm: ["W", "W", "D", "W", "W"],
    isInEuropeanCompetition: true,
  },
  finances: {
    balance: 250_000_000,
    weeklyWageBudget: 5_500_000,
    weeklyWageUsed: 5_300_000,
    incomePerWeek: 8_000_000,
    sponsors: [
      { name: "Qatar Airways", amount: 100_000_000 },
      { name: "Nike", amount: 60_000_000 },
    ],
    ticketPrice: 80,
    merchandising: 45_000_000,
  },
  popularity: {
    fanBaseSize: 18000000,
    fanLoyalty: 72,
    boardExpectations: "Win Ligue 1 and Reach UCL Final",
    boardTrust: 85,
    mediaReputation: 95,
  },
  storyFlags: {
    takeoverRumor: false,
    fanProtest: false,
    historicWin: true,
  },
};
