export type TacticName =
  | "4-3-3"
  | "4-2-3-1"
  | "4-4-2"
  | "4-1-4-1"
  | "4-3-1-2"
  | "4-2-2-2"
  | "4-1-2-1-2"
  | "4-2-4"
  | "3-5-2"
  | "3-4-3"
  | "3-4-1-2"
  | "3-4-2-1"
  | "5-3-2"
  | "5-2-3"
  | "5-2-1-2"
  | "5-4-1"
  | "4-5-1"
  | "4-1-3-2"
  | "4-1-2-3"
  | "4-3-2-1"
  | "3-6-1";

export type Slot = {
  id: string;
  label: string;
  x: number;
  y: number;
};

export const TACTICS: Record<TacticName, Slot[]> = {
  "4-3-3": [
    { id: "GK", label: "GK", x: 50, y: 95 },
    { id: "DG", label: "DG", x: 15, y: 75 },
    { id: "DCG", label: "DCG", x: 35, y: 75 },
    { id: "DCD", label: "DCD", x: 65, y: 75 },
    { id: "DD", label: "DD", x: 85, y: 75 },
    { id: "MCG", label: "MCG", x: 28, y: 55 },
    { id: "MDC", label: "MDC", x: 50, y: 50 },
    { id: "MCD", label: "MCD", x: 72, y: 55 },
    { id: "AIG", label: "AIG", x: 18, y: 25 },
    { id: "AC", label: "AC", x: 50, y: 15 },
    { id: "AID", label: "AID", x: 82, y: 25 },
  ],
  "4-2-3-1": [
    { id: "GK", label: "GK", x: 50, y: 95 },
    { id: "DG", label: "DG", x: 15, y: 75 },
    { id: "DCG", label: "DCG", x: 35, y: 75 },
    { id: "DCD", label: "DCD", x: 65, y: 75 },
    { id: "DD", label: "DD", x: 85, y: 75 },
    { id: "MCG", label: "MCG", x: 35, y: 60 },
    { id: "MCD", label: "MCD", x: 65, y: 60 },
    { id: "MOCG", label: "MOCG", x: 28, y: 40 },
    { id: "MOC", label: "MOC", x: 50, y: 35 },
    { id: "MOCD", label: "MOCD", x: 72, y: 40 },
    { id: "AC", label: "AC", x: 50, y: 15 },
  ],
  "4-4-2": [
    { id: "GK", label: "GK", x: 50, y: 95 },
    { id: "DG", label: "DG", x: 15, y: 75 },
    { id: "DCG", label: "DCG", x: 35, y: 75 },
    { id: "DCD", label: "DCD", x: 65, y: 75 },
    { id: "DD", label: "DD", x: 85, y: 75 },
    { id: "MG", label: "MG", x: 18, y: 55 },
    { id: "MCG", label: "MCG", x: 38, y: 55 },
    { id: "MCD", label: "MCD", x: 62, y: 55 },
    { id: "MD", label: "MD", x: 82, y: 55 },
    { id: "ACG", label: "ACG", x: 40, y: 25 },
    { id: "ACD", label: "ACD", x: 60, y: 25 },
  ],
  "4-1-4-1": [
    { id: "GK", label: "GK", x: 50, y: 95 },
    { id: "DG", label: "DG", x: 15, y: 75 },
    { id: "DCG", label: "DCG", x: 35, y: 75 },
    { id: "DCD", label: "DCD", x: 65, y: 75 },
    { id: "DD", label: "DD", x: 85, y: 75 },
    { id: "MDC", label: "MDC", x: 50, y: 65 },
    { id: "MG", label: "MG", x: 18, y: 50 },
    { id: "MCG", label: "MCG", x: 38, y: 50 },
    { id: "MCD", label: "MCD", x: 62, y: 50 },
    { id: "MD", label: "MD", x: 82, y: 50 },
    { id: "AC", label: "AC", x: 50, y: 15 },
  ],
  "4-3-1-2": [
    { id: "GK", label: "GK", x: 50, y: 95 },
    { id: "DG", label: "DG", x: 15, y: 75 },
    { id: "DCG", label: "DCG", x: 35, y: 75 },
    { id: "DCD", label: "DCD", x: 65, y: 75 },
    { id: "DD", label: "DD", x: 85, y: 75 },
    { id: "MCG", label: "MCG", x: 28, y: 55 },
    { id: "MDC", label: "MDC", x: 50, y: 50 },
    { id: "MCD", label: "MCD", x: 72, y: 55 },
    { id: "MOC", label: "MOC", x: 50, y: 35 },
    { id: "ACG", label: "ACG", x: 40, y: 15 },
    { id: "ACD", label: "ACD", x: 60, y: 15 },
  ],
  "4-2-2-2": [
    { id: "GK", label: "GK", x: 50, y: 95 },
    { id: "DG", label: "DG", x: 15, y: 75 },
    { id: "DCG", label: "DCG", x: 35, y: 75 },
    { id: "DCD", label: "DCD", x: 65, y: 75 },
    { id: "DD", label: "DD", x: 85, y: 75 },
    { id: "MCG", label: "MCG", x: 30, y: 60 },
    { id: "MCD", label: "MCD", x: 70, y: 60 },
    { id: "MOG", label: "MOG", x: 30, y: 40 },
    { id: "MOD", label: "MOD", x: 70, y: 40 },
    { id: "ACG", label: "ACG", x: 40, y: 15 },
    { id: "ACD", label: "ACD", x: 60, y: 15 },
  ],
  "4-1-2-1-2": [
    { id: "GK", label: "GK", x: 50, y: 95 },
    { id: "DG", label: "DG", x: 15, y: 75 },
    { id: "DCG", label: "DCG", x: 35, y: 75 },
    { id: "DCD", label: "DCD", x: 65, y: 75 },
    { id: "DD", label: "DD", x: 85, y: 75 },
    { id: "MDC", label: "MDC", x: 50, y: 60 },
    { id: "MCG", label: "MCG", x: 35, y: 50 },
    { id: "MCD", label: "MCD", x: 65, y: 50 },
    { id: "MOC", label: "MOC", x: 50, y: 40 },
    { id: "ACG", label: "ACG", x: 40, y: 15 },
    { id: "ACD", label: "ACD", x: 60, y: 15 },
  ],
  "4-2-4": [
    { id: "GK", label: "GK", x: 50, y: 95 },
    { id: "DG", label: "DG", x: 15, y: 75 },
    { id: "DCG", label: "DCG", x: 35, y: 75 },
    { id: "DCD", label: "DCD", x: 65, y: 75 },
    { id: "DD", label: "DD", x: 85, y: 75 },
    { id: "MCG", label: "MCG", x: 38, y: 55 },
    { id: "MCD", label: "MCD", x: 62, y: 55 },
    { id: "AIG", label: "AIG", x: 18, y: 25 },
    { id: "ACG", label: "ACG", x: 40, y: 15 },
    { id: "ACD", label: "ACD", x: 60, y: 15 },
    { id: "AID", label: "AID", x: 82, y: 25 },
  ],
  "3-5-2": [
    { id: "GK", label: "GK", x: 50, y: 95 },
    { id: "DCG", label: "DCG", x: 30, y: 80 },
    { id: "DCC", label: "DCC", x: 50, y: 80 },
    { id: "DCD", label: "DCD", x: 70, y: 80 },
    { id: "MG", label: "MG", x: 10, y: 60 },
    { id: "MCG", label: "MCG", x: 30, y: 60 },
    { id: "MDC", label: "MDC", x: 50, y: 60 },
    { id: "MCD", label: "MCD", x: 70, y: 60 },
    { id: "MD", label: "MD", x: 90, y: 60 },
    { id: "ACG", label: "ACG", x: 40, y: 30 },
    { id: "ACD", label: "ACD", x: 60, y: 30 },
  ],
  "3-4-3": [
    { id: "GK", label: "GK", x: 50, y: 95 },
    { id: "DCG", label: "DCG", x: 30, y: 80 },
    { id: "DCC", label: "DCC", x: 50, y: 80 },
    { id: "DCD", label: "DCD", x: 70, y: 80 },
    { id: "MG", label: "MG", x: 10, y: 60 },
    { id: "MCG", label: "MCG", x: 35, y: 55 },
    { id: "MCD", label: "MCD", x: 65, y: 55 },
    { id: "MD", label: "MD", x: 90, y: 60 },
    { id: "AIG", label: "AIG", x: 18, y: 25 },
    { id: "AC", label: "AC", x: 50, y: 15 },
    { id: "AID", label: "AID", x: 82, y: 25 },
  ],
  "3-4-1-2": [
    { id: "GK", label: "GK", x: 50, y: 95 },
    { id: "DCG", label: "DCG", x: 30, y: 80 },
    { id: "DCC", label: "DCC", x: 50, y: 80 },
    { id: "DCD", label: "DCD", x: 70, y: 80 },
    { id: "MG", label: "MG", x: 10, y: 60 },
    { id: "MCG", label: "MCG", x: 35, y: 60 },
    { id: "MCD", label: "MCD", x: 65, y: 60 },
    { id: "MD", label: "MD", x: 90, y: 60 },
    { id: "MOC", label: "MOC", x: 50, y: 45 },
    { id: "ACG", label: "ACG", x: 40, y: 15 },
    { id: "ACD", label: "ACD", x: 60, y: 15 },
  ],
  "3-4-2-1": [
    { id: "GK", label: "GK", x: 50, y: 95 },
    { id: "DCG", label: "DCG", x: 30, y: 80 },
    { id: "DCC", label: "DCC", x: 50, y: 80 },
    { id: "DCD", label: "DCD", x: 70, y: 80 },
    { id: "MG", label: "MG", x: 10, y: 60 },
    { id: "MCG", label: "MCG", x: 35, y: 60 },
    { id: "MCD", label: "MCD", x: 65, y: 60 },
    { id: "MD", label: "MD", x: 90, y: 60 },
    { id: "MOG", label: "MOG", x: 35, y: 35 },
    { id: "MOD", label: "MOD", x: 65, y: 35 },
    { id: "AC", label: "AC", x: 50, y: 15 },
  ],
  "5-3-2": [
    { id: "GK", label: "GK", x: 50, y: 95 },
    { id: "DG", label: "DG", x: 10, y: 75 },
    { id: "DCG", label: "DCG", x: 25, y: 80 },
    { id: "DCC", label: "DCC", x: 50, y: 80 },
    { id: "DCD", label: "DCD", x: 75, y: 80 },
    { id: "DD", label: "DD", x: 90, y: 75 },
    { id: "MCG", label: "MCG", x: 35, y: 60 },
    { id: "MDC", label: "MDC", x: 50, y: 60 },
    { id: "MCD", label: "MCD", x: 65, y: 60 },
    { id: "ACG", label: "ACG", x: 40, y: 25 },
    { id: "ACD", label: "ACD", x: 60, y: 25 },
  ],
  "5-2-3": [
    { id: "GK", label: "GK", x: 50, y: 95 },
    { id: "DG", label: "DG", x: 10, y: 75 },
    { id: "DCG", label: "DCG", x: 30, y: 80 },
    { id: "DCC", label: "DCC", x: 50, y: 80 },
    { id: "DCD", label: "DCD", x: 70, y: 80 },
    { id: "DD", label: "DD", x: 90, y: 75 },
    { id: "MCG", label: "MCG", x: 40, y: 60 },
    { id: "MCD", label: "MCD", x: 60, y: 60 },
    { id: "AIG", label: "AIG", x: 18, y: 25 },
    { id: "AC", label: "AC", x: 50, y: 15 },
    { id: "AID", label: "AID", x: 82, y: 25 },
  ],
  "5-2-1-2": [
    { id: "GK", label: "GK", x: 50, y: 95 },
    { id: "DG", label: "DG", x: 10, y: 75 },
    { id: "DCG", label: "DCG", x: 30, y: 80 },
    { id: "DCC", label: "DCC", x: 50, y: 80 },
    { id: "DCD", label: "DCD", x: 70, y: 80 },
    { id: "DD", label: "DD", x: 90, y: 75 },
    { id: "MCG", label: "MCG", x: 40, y: 60 },
    { id: "MCD", label: "MCD", x: 60, y: 60 },
    { id: "MOC", label: "MOC", x: 50, y: 45 },
    { id: "ACG", label: "ACG", x: 40, y: 15 },
    { id: "ACD", label: "ACD", x: 60, y: 15 },
  ],
  "5-4-1": [
    { id: "GK", label: "GK", x: 50, y: 95 },
    { id: "DG", label: "DG", x: 10, y: 75 },
    { id: "DCG", label: "DCG", x: 25, y: 80 },
    { id: "DCC", label: "DCC", x: 50, y: 80 },
    { id: "DCD", label: "DCD", x: 75, y: 80 },
    { id: "DD", label: "DD", x: 90, y: 75 },
    { id: "MG", label: "MG", x: 18, y: 60 },
    { id: "MCG", label: "MCG", x: 35, y: 60 },
    { id: "MCD", label: "MCD", x: 65, y: 60 },
    { id: "MD", label: "MD", x: 82, y: 60 },
    { id: "AC", label: "AC", x: 50, y: 15 },
  ],
  "4-5-1": [
    { id: "GK", label: "GK", x: 50, y: 95 },
    { id: "DG", label: "DG", x: 15, y: 75 },
    { id: "DCG", label: "DCG", x: 35, y: 75 },
    { id: "DCD", label: "DCD", x: 65, y: 75 },
    { id: "DD", label: "DD", x: 85, y: 75 },
    { id: "MG", label: "MG", x: 18, y: 55 },
    { id: "MCG", label: "MCG", x: 35, y: 50 },
    { id: "MDC", label: "MDC", x: 50, y: 50 },
    { id: "MCD", label: "MCD", x: 65, y: 50 },
    { id: "MD", label: "MD", x: 82, y: 55 },
    { id: "AC", label: "AC", x: 50, y: 15 },
  ],
  "4-1-3-2": [
    { id: "GK", label: "GK", x: 50, y: 95 },
    { id: "DG", label: "DG", x: 15, y: 75 },
    { id: "DCG", label: "DCG", x: 35, y: 75 },
    { id: "DCD", label: "DCD", x: 65, y: 75 },
    { id: "DD", label: "DD", x: 85, y: 75 },
    { id: "MDC", label: "MDC", x: 50, y: 60 },
    { id: "MG", label: "MG", x: 18, y: 40 },
    { id: "MCG", label: "MCG", x: 38, y: 40 },
    { id: "MCD", label: "MCD", x: 62, y: 40 },
    { id: "ACG", label: "ACG", x: 40, y: 15 },
    { id: "ACD", label: "ACD", x: 60, y: 15 },
  ],
  "4-1-2-3": [
    { id: "GK", label: "GK", x: 50, y: 95 },
    { id: "DG", label: "DG", x: 15, y: 75 },
    { id: "DCG", label: "DCG", x: 35, y: 75 },
    { id: "DCD", label: "DCD", x: 65, y: 75 },
    { id: "DD", label: "DD", x: 85, y: 75 },
    { id: "MDC", label: "MDC", x: 50, y: 60 },
    { id: "MCG", label: "MCG", x: 28, y: 40 },
    { id: "MCD", label: "MCD", x: 72, y: 40 },
    { id: "AIG", label: "AIG", x: 18, y: 25 },
    { id: "AC", label: "AC", x: 50, y: 15 },
    { id: "AID", label: "AID", x: 82, y: 25 },
  ],
  "4-3-2-1": [
    { id: "GK", label: "GK", x: 50, y: 95 },
    { id: "DG", label: "DG", x: 15, y: 75 },
    { id: "DCG", label: "DCG", x: 35, y: 75 },
    { id: "DCD", label: "DCD", x: 65, y: 75 },
    { id: "DD", label: "DD", x: 85, y: 75 },
    { id: "MCG", label: "MCG", x: 35, y: 60 },
    { id: "MDC", label: "MDC", x: 50, y: 60 },
    { id: "MCD", label: "MCD", x: 65, y: 60 },
    { id: "MOG", label: "MOG", x: 35, y: 35 },
    { id: "MOD", label: "MOD", x: 65, y: 35 },
    { id: "AC", label: "AC", x: 50, y: 15 },
  ],
  "3-6-1": [
    { id: "GK", label: "GK", x: 50, y: 95 },
    { id: "DCG", label: "DCG", x: 25, y: 80 },
    { id: "DCC", label: "DCC", x: 50, y: 80 },
    { id: "DCD", label: "DCD", x: 75, y: 80 },
    { id: "MG", label: "MG", x: 10, y: 60 },
    { id: "MCG", label: "MCG", x: 30, y: 60 },
    { id: "MDCG", label: "MDCG", x: 40, y: 60 },
    { id: "MDCD", label: "MDCD", x: 60, y: 60 },
    { id: "MCD", label: "MCD", x: 70, y: 60 },
    { id: "MD", label: "MD", x: 90, y: 60 },
    { id: "AC", label: "AC", x: 50, y: 15 },
  ],
};
